### ISSUE TITLE
Dashboard: Display Information about a Trip

### ISSUE THREAD

**Issue by Victoria-Williamson** [Victoria-Williamson/senior-design-mobile#14]
# Should include the creation of 

- [x]  Join Event UI component
- [x]  Itinerary UI Component
- [x]  Header UI Component

**Comment by aamare1001** [comment]
<img width="171" alt="image" src="https://user-images.githubusercontent.com/26231761/220204496-094fd3d9-e054-413b-91ab-2c1e8089600e.png">

**Comment by aamare1001** [comment]
<img width="259" alt="image" src="https://user-images.githubusercontent.com/26231761/223018531-26c7d94f-d652-4a39-8359-8be720d0abb8.png">
Current EventInfo Popup
