### ISSUE TITLE
User Settings

### ISSUE THREAD

**Issue by Victoria-Williamson** [Victoria-Williamson/senior-design-mobile#22]
# Forms for modifying

- [ ] profile picture ( stretch )
- [ ] Personal information
- [ ] Emergency Information
- [ ] Change email
- [ ] Change password

**Comment by aamare1001** [comment]
![image](https://user-images.githubusercontent.com/26231761/223018727-226b8754-57e6-4e1d-8aea-d3743d55746f.png)
